### ISSUE TITLE
Data For Running Analysis

### ISSUE THREAD

**Issue by Fore7630** [RGLab/MASTdata#4]
Hi,

I have a question regarding the data that you used for your GSEA analysis:

Where on this github repository could I find the code you used to load the MastDataPackage containing the data into R?

Thanks,
Corey

**Comment by gfinak** [comment]
I'm sorry, I don't quite understand what you are looking for. The MASTData repository has the data and the vignettes. What exactly are you missing?

Greg Finak

**Comment by Fore7630** [comment]
What is the best way to load the Data from the repository into R?
I have tried loading the data in using `"devtools::install_github("RGLab/MASTdata")."` However I am getting an SSL connect error. I have also tried using `load(pathtoMastDatapackage.rda).` However, I am getting an error as well: 
`Error in nrow(x@elementMetadata) : 
  no slot of name "elementMetadata" for this object of class "SingleCellAssay"`

Is there a better way to load the data into R from the repository? 

Thanks,
Corey

**Comment by gfinak** [comment]
Oh, I bet the format of the single cell objects in the package is not
compatible with the new MAST version. You should install the version of
MAST used to generate the figures for the paper. We've changed the
underlying data structures in the package since the paper was published.
As far as your ssl error, I don't know what's going on there. Perhaps just
clone the repo and run R CMD INSTALL.

**Comment by Fore7630** [comment]
I have identified the MAST version as 1.0.1 from the package name in the paper. Is this correct?
If so, do you know where I can possibly find this older version of MAST?

Thanks,
Corey

**Comment by gfinak** [comment]
Please see issue #3  this has been addressed there.

**Comment by Fore7630** [comment]
Thank you so much for the information, I will follow that discussion to resolve this issue!

**Comment by Fore7630** [comment]
Sorry to bother you again, but after looking at the MAST directory, I am having trouble distinguishing which folder your MASTClassic branch code is located.

**Comment by gfinak** [comment]
It's in the MASTClassic branch of the repository. It's not a folder, it's a
branch of the git repository.

Greg Finak

**Comment by Fore7630** [comment]
I have found the branch. Thank you for your help!

Corey Li

**Comment by Fore7630** [comment]
I read on your paper that you utilized FASTQ files to obtain your data for the analysis. I currently have FASTQ files from 10x genomics 3' Single Cell Experiments. Do you know if your MAST package works with that kind of data?

**Comment by gfinak** [comment]
Yes, you'll need to align to a genome, summarize the gene counts and transform to TPM. We used RSEM, but STAR should also work.
Best,
Greg

**Comment by Fore7630** [comment]
That is great news! I have one last question. When you imported the TPM matrix into MAST, what is the layout of that matrix. Is it a matrix with Genes x Cell with TPMs as the values in the matrix?

Thanks,
Corey

**Comment by gfinak** [comment]
That will depend on whether you are using MASTClassic or the newer version. I recommend, if you are not trying to reproduce analysis from the paper, but rather working on your own data set, then use the master branch (i.e. The version in BioConductor). It is based around a SummarizedExperiment object. The matrix of expression can be extracted as described in the package vignette. 
MASTClassic stores genes as columns. The newer version stores genes as rows. 
I do suggest looking at the vignettes in the package.

**Comment by Fore7630** [comment]
By **package vignette** do you mean the files located in the Vignettes folder of the master branch in the RGLab/MAST github repository?

**Comment by gfinak** [comment]
If you load the package via `library()` and call `vignettes(package="MAST"` you will see a list of compiles vignettes in the package that describe how to use the package.

**Comment by Fore7630** [comment]
I have extracted the data matrix. Thank you so much!

Best,
Corey
