### ISSUE TITLE
Enrichment Plot for GSEA

### ISSUE THREAD

**Issue by Fore7630** [RGLab/MASTdata#5]
Hi,

I was wondering if MAST is able to produce enrichment plots such as these on the GSEA website:
http://software.broadinstitute.org/gsea/doc/ug_images/anl-enrichment-geneset-plot-annotated.gif
but for single cell data?

Best,
Corey Li

**Comment by gfinak** [comment]
The GSEA algorithm of Subramanian et al.  is fundamentaly different than  what is implemented in MAST. MAST does something more akin to the algorithm implemented by CAMERA.

See the following paper:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3458527/

 

Greg

**Comment by Fore7630** [comment]
We have a list of signatures that we want to query against our gene expression data. Although the implementation in MAST is different than Subramanian et al. is it possible to do this with your package?

**Comment by gfinak** [comment]
Of course. Follow the vignette. You just need to map the gene names in a
signature  to gene indices in the expression matrix.

**Comment by Fore7630** [comment]
Thank you for the confirmation. 
On the vignette it states that the BioC version of MAST does not need the summarizedExpt branch of MAST. Is the BioC version the one installed from the BiocLite source via `source("https://bioconductor.org/biocLite.R")`
`biocLite("MAST")`
?
Corey

**Comment by gfinak** [comment]
The BioC version definitely uses summarized experiment. The vignette might
be a bit outdated referring to the development version. Thanks for pointing
it out.

Greg Finak

**Comment by Fore7630** [comment]
I apologize for the late reply. 

One last issue I have before analysis is that I currently only have a matrix of normalized gene expression values, no convariate data or . For flattened data, your vignette describes the `FromFlatdf()` function as a possible alternative. I have followed the directions and constructed a data table of the gene IDs, cell IDs, and normalized expression values from `melt()` function and subsequently used FromFlatdf() to construct the SCA object. After running the first function, `aheatmap(),` I get an error:
`Error: subscript contains invalid names. ` 

I fear that this may have stemmed from the formatting of the data table. Do you know what is the format of the data table that FromFlatdf() is looking for?

Thanks,
Corey

**Comment by gfinak** [comment]
It's going to be very difficult to diagnose this problem without some
reproducible code. Perhaps start with the examples and try to get your data
into that form?

**Comment by Fore7630** [comment]
Do you perhaps know what kind of data format is needed for the `FromFlatDF()` function described in your vignette? 

Thanks,
Corey

**Comment by Fore7630** [comment]
Is it possible to input only a normalized expression matrix and analyze using MAST? Our pipelines never generated any covariates nor are we attempting to analyze any covariates associated with the expression data.

Thanks,
Corey

**Comment by gfinak** [comment]
You are surely looking at some contrast (e.g. treated vs untreated), and
you'd at least want to control for CDR (cellular detection rate) as a
covariate.


Greg Finak

**Comment by Fore7630** [comment]
Hi, 

We do have two phenotypes that we want to test. However, it seems like that you are using many of your covariates in your downstream analysis, such as bootstrapping using cngeneson factor. Do you know where you generated all of these covariates? Were they generated automatically through RSEM or were they all generated manually? Also is ngeneson simply a list of how many genes with non-zero tpm values are in each cell?

Best,
Corey

**Comment by gfinak** [comment]
The downstream model should be the same model used to test differential
expression of individual genes. cngeneson is the proportion of non zero
genes in a cell, centered around the mean across all cells. It is computed
manually from the data and added to the single cell assay object cell level
annotations. You can include that covariate as well as one for your
phenotype, you would then look at the coefficients for the phenotypes to
find differentially expressed genes, or for GSEA, gene sets enriched
(either positively or negatively), with your phenotype of interest.
If you can provide more information or some code, I could be more helpful.
This is all rather vague and general at the moment.

Greg Finak

**Comment by Fore7630** [comment]
I've added covariates such as nGenesOn and primerIDs to the expression matrix and have followed the vignette for the GSEA analysis until this error: 
`Error in names(dimnames(out3d)) <- c("set", "comp", "metric") : 
  'names' attribute [3] must be the same length as the vector [2]` 
from the 
`z_stat_comb <- summary(gsea, testType='normal')` function.
I have manually imported a gene list from external sources, converted it to a character vector list, and indexed them using limma. Do you know what could be causing this error?

Corey Li

**Comment by gfinak** [comment]
Can you kindly provide a minimal example of code and data that produces this error?

**Comment by Fore7630** [comment]
I have an expression matrix(cells by geneID matrix with non-expressed genes removed), a features matrix(with wellkey, nGenesOn, and condition as features), and a gene ID matrix exactly matching the IDs in the expression matrix. I loaded this data in using 
`scarenilla <- FromMatrix(t(transformedmat1), celldatatab, genedatatest)`
I did not do any filtering since this is simply a test to see whether the commands worked. I assumed that the filtering will not significantly alter any parameters which may be involved in subsequent analysis. 
I subsequently generated the hurdle model conditions using the following lines: 
`cdr2 <-colSums(assay(sca)>0)`
`colData(scarenilla)$cngeneson <- scale(cdr2)`
`cond<-factor(colData(scarenilla)$condition)`
`cond<-relevel(cond,"unstim")`
`colData(scarenilla)$condition<-cond`
`zlmCond <- zlm(~condition + cngeneson, scarenilla)`
I also generated a list of character vectors with differing lengths, representing gene lists, and here is what I get when I view the character vector list on the console:
> genelist
[[1]]
 [1] "Meis1"   "Hoxa9"   "Hoxa10"  "Mef2c"   "Mylk"    "Hoxa5"   "Mef2c"  
 [8] "Peli1"   "Stau2"   "Runx2"   "Laptm4b"
[[2]]
  [1] "Shmt1"         "Zmym1"         "Meaf6"         "Usp37"        
  [5] "Msh6"          "Rbbp4"         "Bri3bp"        "Rrp8"         
  [9] "Mb21d1"        "Wdhd1"         "Mcm5"          "Smarca5"      
 [13] "Slc1a5"        "Nap1l4"        "Nolc1"         "D10Wsu102e"  

I indexed these using `sets_indices <- limma::ids2indices(genelist, mcols(scarenilla)$symbolid)` and then ran 
`boots1 <- bootVcov1(zlmCond, R=4)`
`gsea1 <- gseaAfterBoot(zlmCond, boots1, sets_indices, CoefficientHypothesis("conditionstim"))` 
`z_stat_comb <- summary(gsea1, testType='normal')` for the GSEA.
However, after running the last command on the GSEA object, I get the error: 
`Error in merge.data.table(t_stat_wide, pvals, by = "set") : 
  Elements listed in by must be valid column names in x and y`
 `In addition: Warning message:
  In [<-.data.table(x, j = name, value = value) :
  Adding new column 'set' then assigning NULL (deleting it).`

Thanks,
Corey

**Comment by gfinak** [comment]
I can't help you unless you provide reproducible code and data. I don't know what your data looks like. I know what you tell me it looks like, but I can't verify it, I can't run the code you posted.

- A minimal reproducible example consists of the following items:

    1. a minimal dataset, necessary to reproduce the error
    2. the minimal runnable code necessary to reproduce the error, which can be run on the given dataset.
    3. the necessary information on the used packages, R version and system it is run on.

**Comment by Fore7630** [comment]
I am currently in the process of testing a minimal data set. In the meantime, do you perhaps know how I can see the source code for your GSEA summary method?

Corey

**Comment by gfinak** [comment]
`methods("summary")` will print a list of all methods defined for "summary".
`getMethod("summary","GSEATests")`, will print the source for the one you're interested in.

**Comment by Fore7630** [comment]
Thank you so much! I have found the problem and fixed it and the graph is successfully generated. I am also wondering how well does your GSEA test work with non-tpm values. I have simple read counts normalized to the median and log reduced. Will the test results generated from these values be accurate?

**Comment by gfinak** [comment]
I really can't say whether you can trust the inferences from log count values.
